CREATE DATABASE chatAPP;

USE chatAPP;

CREATE TABLE `user_tbl` (
	id INT AUTO_INCREMENT NOT NULL
	,`username` VARCHAR(30) NOT NULL
	,`password`	VARCHAR(30) NOT NULL
    ,`logged_in` TINYINT DEFAULT 1
	,`createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP
	,`updatedAt` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (id)
);

CREATE TABLE `post_tbl` (
	`id` INT AUTO_INCREMENT NOT NULL
	,`image` VARCHAR(255) NOT NULL
	,`caption` VARCHAR(255)
	,`createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP
	,`updatedAt` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
	,`userId` INT NOT NULL
	,PRIMARY KEY (`id`)
	,FOREIGN KEY (`userId`) REFERENCES `user_tbl` (`id`)
);

CREATE TABLE `comment_tbl` (
	`id` INT AUTO_INCREMENT NOT NULL
	,`comment` VARCHAR(255) NOT NULL
	,`createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP
	,`updatedAt` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (`id`)
	,`textId` INT NOT NULL
	,`userId` INT NOT NULL
	,FOREIGN KEY (`textId`) REFERENCES `post_tbl` (`id`)
	,FOREIGN KEY (`userId`) REFERENCES `user_tbl` (`id`)
);
